### ISSUE TITLE
Demoapp not working with DataWedge v 6.2.24 at TC8000 scanner

### ISSUE THREAD

**Issue by EasyStep2Lean** [Zebra/ZebraIonicDemo#1]
Hi Darryn,

We ran into your nice Ionic Example, and trying it to get it working at a borrowed Demo TC8000 scanner. However what ever we try with the manual DataWedge setup, since we have gotten a model with a DataWedge 6.2.24 version, its not responding at all with the Scan button. The Fab button is disabled due to the lower version of the DataWedge. Any Ideas how to get the demo working so we can start porting it into our own app. 

regards,

Rick

**Comment by darryncampbell** [comment]
Hi Rick,

I don't have a TC8000 available to test with unfortunately but the basic scanning functionality should work.  The problem would either be with the DW configuration to send intents or perhaps some problem with the application registering to receive intents.  I am attaching an exported DW profile which hopefully you can load on your device to account for the former.  For the latter, you might try connecting to the device with Chrome via chrome://inspect to see if there are any errors in the console or perhaps see if there are any issues in logcat  
[dwprofile_ZebraIonicDemo.zip](https://github.com/Zebra/ZebraIonicDemo/files/1963927/dwprofile_ZebraIonicDemo.zip)

**Comment by EasyStep2Lean** [comment]
that's great, I will test it right now, looks like the button at the grip is not responding towards anything. Perhaps some hidden key mapping at this scanner:-(

**Comment by EasyStep2Lean** [comment]
noop, no result

**Comment by darryncampbell** [comment]
If it's not even scanning anything at all then perhaps DataWedge is disabled or yes, some other issue with the device which might be resolved with a factory reset.

**Comment by EasyStep2Lean** [comment]
Thanks, I will ask the vendor from who we borrowed it. Probeley see you tommorrow in the webinar for Ionic and Zebra

**Comment by EasyStep2Lean** [comment]
Touch down, after a Enterprise Factory Reset everything start working. Thanks for your help and support.
ps The demoapp should have an "If platform.ready() { <your code> }  around your code in the constructor of home.ts and barcode.ts to ensure excuting of the code after Ionic is loaded correctly.
If you want I can attach both files

**Comment by darryncampbell** [comment]
Glad it's working & thanks, good point about platform.ready().  I will make the change locally but wont push it for a few days as I don't want to break anything before the webinar later.
