### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by invot** [Zebra/ZebraIonicDemo#11]
This project no longer seems to build. Also, will you be adding support for ionic v4 anytime soon?

**Comment by darryncampbell** [comment]
Hi, what build issues are you seeing?  I tried this morning and resolved the few issues I saw in a branch: https://github.com/Zebra/ZebraIonicDemo/tree/20191205_build_issues

Regarding Ionic v4, I have set myself a reminder to look at that between Christmas & new year when most other people are out the office

**Comment by invot** [comment]
Wow. Thank you for such a quick response! I'll dabble with your new branch and let you know if anything weird happens. 

I'm curious to see what kind of work is involved in migrating from version 3 to 4. If it's just different namespaces or whatnot, I might give it a try and submit a pull request.

**Comment by darryncampbell** [comment]
Regarding Ionic v4, please see this comment: https://github.com/Zebra/ZebraIonicDemo/commit/c0338cfa05cb45b97bb294578f71cbe219fd0ead#diff-04c6e90faac2675aa89e2176d2eec7d8 .  I believe this issue can now be closed?

**Comment by invot** [comment]
I think this issue can be closed, yes.
