### ISSUE TITLE
Data Wedge Version 86.2.23

### ISSUE THREAD

**Issue by liviso** [Zebra/ZebraIonicDemo#2]
I have a CC5000 verifier, the data wedge version is 86.2.23.
What version is equivalent to 86.2.23?

Is there any way to integrate this version of Data wedge to configure the profile from code, instead of creating the profile manually?

![img_6426-01-06-18-08-23](https://user-images.githubusercontent.com/12677117/40842997-316245bc-6575-11e8-9483-40379b441189.JPG)

**Comment by darryncampbell** [comment]
There is always a strange edge case.  The CC5000 version of DataWedge is a sort of offshoot from the main product line.  You might not have access to the DW API but you should still be able to achieve basic scanning if you create the profile manually as described in the ReadMe file https://github.com/Zebra/ZebraIonicDemo/blob/master/README.md.
