### ISSUE TITLE
Error running the app in the browser and device in live mode

### ISSUE THREAD

**Issue by kurtommy** [Zebra/ZebraIonicDemo#4]
Hi @darryncampbell 

I'm developing an Ionic app for Zebra tc51/56 i've cloned this repo and running

ionic serve or ionic cordova run android --device -l

that make sense in browser (a fallback when the hardware is not detected would be great) but in development mode with the device connected via USB that should work

running only ionic cordova run android --device without the -l flag it works.
the profile is present in the DataWedge app.

i'll get this error:

![screenshot 2018-11-26 at 15 56 38](https://user-images.githubusercontent.com/2192625/49022033-34e9ee00-f194-11e8-9cbc-f34378d18730.png)

Do you have an idea? The device is running Android 6.0.1

**Comment by darryncampbell** [comment]
Hi, I am currently on PTO but will take a look when I return

**Comment by kurtommy** [comment]
@darryncampbell do you mind if i ask when you'll be back or if i can get help from another Zebra dev? we are working for a major worldwide fashion brand in a new integration for their logistic system we'd like to develop a  ionic app instead of native but with this error is very hard to test the DataWedge

thanks a lot

**Comment by EddieCorreia** [comment]
Hi Tommaso-

Thank you for contacting Zebra.

I suggest that you submit your question to the DataWedge community forum:

https://developer.zebra.com/community/home/discussions/datawedge

Best regards,
Eddie Correia
Enterprise Mobile Computing
Techdocs, Tools and Community
ZEBRA TECHNOLOGIES CORPORATION
edward.correia@zebra.com
techdocs.zebra.com
www.zebra.com
________________________________________

**Comment by darryncampbell** [comment]
Hi, the application depends on a plugin.  I don't believe it is possible to use a custom plugin with Ionic serve.  Running with -livereload is more interesting, I see other posts about this as a more general issue (e.g. this one: https://github.com/ionic-team/ionic-app-scripts/issues/1354), if so, I do not think it would be an issue with this plugin.
