### ISSUE TITLE
Request : Show the scanner preview while scanning

### ISSUE THREAD

**Issue by akilude** [Zebra/ZebraIonicDemo#6]
Hi,

I'm using a TC25 and the DataWedge works well on the ionic app, I'm stuck on how to show the preview of the scanner with the target "+" mark like the datawedge demo app, Any idea on how to show the preview while scanning?

Thanks,
Akil

**Comment by EddieCorreia** [comment]
Hi-

Thank you for contacting Zebra. I suggest that you post your question in the DataWedge developer forum:

https://developer.zebra.com/community/home/discussions/datawedge


Eddie Correia
Enterprise Mobile Computing
Techdocs, Tools and Community
ZEBRA TECHNOLOGIES CORPORATION
________________________________________

**Comment by darryncampbell** [comment]
Hi, also, I suggest you compare the DataWedge profile for DWDemo with the Profile created by the Ionic app (ZebraIonicDemo unless you change it in the app).  You can find both these profiles by launching the DataWedge app on the device.

**Comment by akilude** [comment]
Thank you, ive cloned the DWDemo Profile and now it does show the preview while scanning, will compare the both and see what enabled the preview.

**Comment by akilude** [comment]
The Picklist option in the reader params toggles the scan preview.
